<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="5" tests="20" name="apiTestCases.GetUserInfoTest" time="27.804" errors="0" timestamp="2024-08-26T13:35:59 IST" skipped="15">
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.395">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.512">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.330">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="2.524">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.208">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.461">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.402">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.250">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.310">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.193">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.185">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.272">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.375">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.224">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.428">
    <failure message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.381">
    <failure message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.282">
    <failure message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.332">
    <failure message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.493">
    <failure message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <system-out/>
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.247">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <system-out/>
</testsuite> <!-- apiTestCases.GetUserInfoTest -->
